import sqlite3
from sqlite3 import Error
import os

dirname = os.path.dirname(__file__)
dbpath = os.path.join(dirname, "database")
imge_path = os.path.join(dirname,"images")
print(dbpath)

#this func creates a connection with our database
def create_connection(db_file):
    conn = None
    try:
        #Creates a connection 
        conn = sqlite3.connect(db_file)
        print("Connection successs")
    
    except Error as e:
        print(e)
    
    return conn

    # finally:
    #     if conn:
    #         #clse the connection
    #         conn.close()

#Func to create ouur tables
def create_table(conn, create_table_sql):
    try:
        cur = conn.cursor()
        cur.execute(create_table_sql)
        print("table created")
    except Error as e:
        print(e)


#FUnc to insert data into Categpry table
def create_Category(conn, category):
    sql = '''
            INSERT INTO Category(name, image)
            VALUES(?, ?)
            '''
    cur = conn.cursor()
    cur.execute(sql, category)
    conn.commit()
    #return cur.lastrowid    #To get the generated id


#Funct to insrt data into the recipe table
def create_Recipes(conn, recipes):
    sql = '''
            INSERT INTO Recipes(name, steps, image, duration, requirements, popularity, Cat_name)
            VALUES(?, ?, ?, ?, ?, ?, ?)
            '''

    cur = conn.cursor()
    cur.execute(sql, recipes)
    conn.commit()
    # return cur.lastrowid

#The main func that performs all the task tgether
def main():

    database = f"{dbpath}/recipiaData.db"

    #Write down syntax for the creation of our table
    sql_create_Category_table = """ CREATE TABLE IF NOT EXISTS Category (
                                    id integer PRIMARY KEY,
                                    name text UNIQUE NOT NULL,
                                    image text
                                ); """

    sql_create_Recipes_table = """ CREATE TABLE IF NOT EXISTS Recipes (
                                    id integer PRIMARY KEY,
                                    name text UNIQUE NOT NULL,
                                    steps text NOT NULL,
                                    image text,
                                    duration text,
                                    requirements text,
                                    popularity integer,
                                    Cat_name text,
                                    FOREIGN KEY(Cat_name) REFERENCES Category(name)
                                ); """


    #connect to our database
    conn = create_connection(database)

    #create the table
    if conn is not None:
        #create the category table
        create_table(conn, sql_create_Category_table)
        
        #create the recipes table
        create_table(conn, sql_create_Recipes_table)


    else:
        print(" Error connecting to the database")



    with conn:
        
    #Create Category var and store in the Category table
        cat_1 = ('Soups', f'{imge_path}/Category Images/Soups.jpg')
        cat_2 = ('Cereal', f'{imge_path}/Category Images/Cereal.jpg')
        cat_3 = ('Vegetables', f'{imge_path}/Category Images/Vegetables.jpg')
        cat_4 = ('Salads', f'{imge_path}/Category Images/Salads.jpg')
        cat_5 = ('Stews', f'{imge_path}/Category Images/Stews.jpg')
        cat_6 = ('Sauce', f'{imge_path}/Category Images/Sauce.jpg')
        # cat_7 = ('Curry', f'{imge_path}/Category Images/Curry.jpg')
        # cat_8 = ('Baked', f'{imge_path}/Category Images/Baked.jpg')
        # cat_9 = ('Fries', f'{imge_path}/Category Images/Fries.jpg')
        # cat_10 = ('Roast', f'{imge_path}/Category Images/Roast.jpg')
        cat_7 = ('Others', f'{imge_path}/Category Images/Curry.jpg')

        #Now add the Category to the database
        create_Category(conn, cat_1)
        create_Category(conn, cat_2)
        create_Category(conn, cat_3)
        create_Category(conn, cat_4)
        create_Category(conn, cat_5)
        create_Category(conn, cat_6)
        create_Category(conn, cat_7)
        # create_Category(conn, cat_8)
        # create_Category(conn, cat_9)
        # create_Category(conn, cat_10)
        def add_recipe():
            for a in range(1,48):
                create_Recipes(conn, f'rec_{a}')

        #Now for recipes
        rec_1 = ('Eru the Cameroonian Style', '1 Boil the smoked kidney meat and cow skin with a bit of salt, maggi bouillon, spring onion and pepper. You can also boil cod fish if it is too strong. :2 Boil with a bit of water, about 3 cups, depending on the quantity of meat. Make sure it is ready and soft. :3 Wash the eru. Put it in a colander to drain, then wash the sliced water leaf or spinach also, and drain. :4 Add the water leaf or spinach. When the kidney meat and cow skin are ready, together with the cod fish. :5 Add the water leaf or spinach and leave for a few minutes. Stir the water leaf or spinach and make sure it looks cooked. :6 Now add the eru while stirring. Be aware that this process is very delicate because you need to make sure you don\'t put in more eru than the water leaf or spinach can take. :7 Pour in the palm oil and add the cod fish if you didn\'t do so at the beginning. Leave for a while to cook. Beware; don\'t cover the pot. :8 Make sure to remove all the bones in the fish before putting it in the pot. Add the pepper, cray fish (ground to a dusty powder), shrimps, maggi bouillon and salt. :9 You could add the chilli pepper but this is optional. In just a few minutes, your eru is ready. :10 Serve. It can be served with pounded fufu, water fufu, garri, in short anything fufu made from cassava. Enjoy!', f'{imge_path}/Eru.jpg', '2 Hours','1:Water Leaf or Spinach, 2:Eru, 3: maggi, 4:salt, 5:cod fish or meat', '4.7', 'Vegetables')

        rec_2 = ('Australia\'s most popular pumpkin soup', '1 Heat oil a large saucepan over low heat, add onion and leek and cook for 2-3 minutes, until softened but not coloured. :2 Add garlic and spices and cook, stirring, for 30 seconds. Add pumpkin, potato and stock and bring to the boil. Turn heat to low, cover and simmer for 30 minutes. :3 Allow to cool slightly, then blend in batches. :4 Return soup to pan, stir through cream and reheat gently. Season and add a little more nutmeg if desired.', f'{imge_path}/pumpkin soup.jpeg', '1 Hour', '1:oil, 2:onion, 3:garlic and spices, 4:pumpkin, 5:potato, 6:stock', '4.0', 'Soups')
        
        rec_3 = ("White Bean Chicken Soup","1 Heat the oil in a large pot set over medium heat. :2 Sauté onions, carrots, celery, jalapeño and bay leaf until vegetables are onions are tender, about 5 minutes. Add garlic and cook for 2 more minutes. :3 Add chicken stock, beans, shredded chicken, salt and pepper and dill. Bring to a boil then reduce to a swimmer. Simmer for 20 minutes stirring occasionally. :4 Add chard and lemon juice and simmer for another 10 minutes. If you like it a little bit more 'bright' add more lemon juice. :5 Serve. Garnish with more dill, a squeeze of lemon juice and a little parmesan, if you’d like to.", f'{imge_path}/White Bean Chicken Soup.jpg', '35 mins', '1: 2 tbsp of Olive oil or groundnut oil, 2: 1 Onion (finely diced), 3: 2 Large carrots (peeled and diced), 4: 2 Celery stalks (finely diced), 5: 1 Jalapeño; seeds removed and finely diced (optional), 6: 1 Bay Leaf, 7: 3 Garlic cloves (minced), 8: 8cups of Chicken stock, 9: 2(14 oz cans) Cannellini beans (drained and rinsed), 10: 1tsp salt, 11: Shreded Chicken, 11: 1/2 tsp of ground pepper, 12: 2tbsp of Fresh dill (finely chopped plus extra for garnish), 13: Lemon (juiced), 14: Swiss chard (stems removed and roughly chopped), 15: Parmesan cheese for serving ', '4.2', 'Soups' )

        rec_4 = ("Chicken Noodle Soup", "1 Heat the butter or olive oil in a large pot set over medium heat. Add the onion, celery and carrots and cook until the onions are translucent, about 5 minutes. :2 Add garlic and cook for 1 minute longer. :3 Add the chicken stock, bay leaves. Bring to a boil over high heat. Reduce heat to medium and cook until the vegetables are tender, about 15 minutes. :4 Add the chicken, egg noodles, parsley, salt and pepper. Maintain a low boil until the noodles are tender and the chicken is warmed through.",f'{imge_path}/Chicken Noodle Soup.jpg',"20mins", "1: Olive oil or groundnut oil or butter, 2: 1 Small yellow onion (chopped about 3/4 cup), 3: 2 Ribs of celery (1/2-inch chopped), 4: 1-2 Large carrots (peeled and 1/2-inch sliced about 1 1/2 cups), 5: 4 Cloves garlic (minced), 6: 2 Bay leaves, 7: 8cups of Chicken stock, 8: 6oz Egg noodles, 9: 1tbsp salt, 9: 1tbsp Minced flat leaf parsley, 10: 1/4tbsp Fresh cracked black pepper to taste", "4.0", "Soups" )


        rec_5 = ("African Peanut Soup","1 In a large pot heat olive oil over medium heat. Add onions and sauté until softened, about 3-4 minutes. :2 Add in ginger, jalapeno and garlic and stir until fragrant about 1 min. :3 Add the pepper, cumin and tomato paste and cook for another 2 minutes, stirring, until paste darkens. :4 Add the crushed tomatoes, stock, sweet potatoes, chickpeas and peanut butter. Bring to a boil and stir until fully combined. :5 Turn the heat down to low and simmer for 15 minutes, until sweet potatoes are tender.Add in kale and shredded chicken and cook for another 5 minutes. :6 Taste the soup before adding salt. Depending on how salty your stock and/or peanut butter was, it may not need anymore salt. :7 If you use low sodium stock and salt-free peanut butter, it will need a full teaspoon salt, maybe more. Adjust to your own liking. :8 Serve warm topped with cilantro and crushed peanuts. Enjoy!",f'{imge_path}/African Peanut Soup.jpg',"35mins", "1: 2tbsp Olive oil or groundnut oil, 2: 1 Medium onion (chopped 1 cup), 3: Ginger (minced), 4: 1 Jalapeño (seeds and ribs removed and diced), 4: 4 Garlic cloves (minced), 5: Pepper, 6: 2tbsp Tomato paste, 7: Cumin, 8: 1 can Crushed tomatoes, 4 cups Chicken stock, 9: 1tbsp Salt (to taste), 10: 1 Sweet potato (peeled and diced), 11: 1 can Chickpeas (drained), 12: 1 cup Creamy natural peanut butter, 13: 4cups Kale (roughly chopped), 14: Peanuts (crushed), 15: 1.5Ibs Chicken (poached shredded), 15: Cilantro (chopped (optional) for garnish) ", "4.0", "Soups")

        rec_6 = ("Achu Soup (Yellow Soup)", "1 In medium –sized saucepan boil meat, season with salt, hot pepper, and Maggie until tender (approximately 30-60 minutes depending on the choice of meat). :2 You can shorten this process in half by using a pressure cooker. Reserve the stock (preferably 6 cups or more). :3 Boil the cow skin and tripe together or you may do so separately until tender. :4 Remove cow skin, tripe. Set aside Let the stock come to room temperature before using. :5 While meat is boiling grind limestone and warm, :6 In a blender, pulse stock, limestone, oil and achu spice, until all the ingredients have been fully incorporated and it has turned into yellowish color. :7 Adjust salt and Maggie according to taste.", f'{imge_path}/Achu Soup.jpg', "1hr 10mins", "1: 1-2 pounds of assorted meat beef, tripe, cow skin, 2: 6-7 cups stock or/and water, 3: 1 tablespoon bouillon powder or maggie, 4: 2 tablespoon ground achu spice, 5: 1/2 cup warm red oil, 6: 1 hot pepper Scotch bonnet/Habenero, 7: 1 tablespoon ground limestone ,8: Salt to taste","4.6","Soups")

        rec_7 = ("Ogbono Soup", "1 In medium –sized saucepan boil meat, season with salt and pepper until tender (approximately 30-60 minutes depending on the choice of meat). :2 You can shorten this process in half by using a pressure cooker. Boil the cow skin and tripe together or you may do so separately until tender. :3 Use best judgement . Remove cow skin, tripe and add to the pot of boiled meat. Add smoked fish, if using any. :4 Be sure to have enough stock from the meat (about 3-4 cups). :5 Mix ground ogbono with red oil, then add to the pot of boiled meat, followed by crayfish and scotch bonnet pepper, bring to a boil. :6 Simmer and let it cook for about 10 minutes or more. :7 Add chicken bouillon or cubes, if desired. :8 Add more stock water as needed to get to desired thickness. Then add spinach cook for another 2-3 minutes, turn stove off and serve piping hot.", f'{imge_path}/Ogbono Soup.jpg', "1hr 10mins", "1: 1-2 pounds meat , (oxtail , stew beef , tripe and kpomo (cow skin) ), 2: 1/2 cup ground Crayfish, 3: 1 cup smoked fish, 4: 1 cup diced onion, 5: 1/4 – ⅓ cup palm oil, 6: 1 tablespoon chicken bouillon (adjust to taste bud), 7: 3 cups chopped greens (spinach; collard greens; kale; callaloo (African greens) ), 8: 1/2 cup ground ogbono, 9: 1/4 – ⅓ cup palm oil, 10: 1/2 cup ground egusi (optional), 11: 1 tablespoon red pepper flakes ", "4.2", "Soups")

        rec_8 = ("Okro Soup", "1 In medium –sized sauce pan boil oxtail seasoned with garlic salt, smoked paprika, pepper and onions until tender (approximately 30 -40 minutes). :2 You can shorten this process in half by using a pressure cooker. :3 If using fresh okra wash the okra, remove the tops and tails, and slice into rounds. :4 Blend the okra to a coarse consistency in a food processor or you can finely chop the okra into coarse consistency using a sharp knife. :5 Add the ground crayfish, bouillon or Maggie and egusi into the pan of boiled meat , cook for 5 minutes. :6 Then add shrimp, cook for another 5 minutes and finally add the spinach and stir for about a minute or 2 . :7 Then add shrimp, cook for another 5 minutes and finally add the spinach and stir for about a minute or 2 ", f'{imge_path}/Okro Soup.jpg', "50mins", "1: One pound okra fresh or frozen, 2: 1/2 pound Shrimp, 3: 1/2 pound meat oxtail, 4: 1 tablespoon Beef or chicken bouillon, 5: 1/2 cup ground Crayfish, 6: 1/2 cup medium –sized Onions chopped, 7: 3 cups of chopped Spinach, 8: 1 tablespoon red pepper flakes, 9: 1 tablespoon smoked paprika, 10: 1/2 cup ground Egusi (optional), 11: Salt and pepper to taste", "4.3", "Soups")

        rec_9 = ("Cream Of Mushroom Soup", "1 Damp a paper towel then use this to clean mushrooms one at a time. Wipe the outside and underside to remove any dirt. :2 If using small mushrooms, rinse under cold water, then pat dry with paper towels. :3 Bring a large skillet or cast iron on medium to high heat. Then add oil, swirl to coat bottom the pan. :4 Add mushrooms, season with salt and Creole seasoning – stir for a few minutes until slightly brown. Set aside,:5 Add butter to the skillet, followed by onion, cook , stirring until tender and translucent - about 3-5 minutes. Do not brown the onion. :6 Next, add garlic and thyme, stir for about a minute. Stir in flour and continue cooking for another minute until flour and onions are well combined. :7 Pour in chicken stock, followed by evaporated milk,  a little at a time until it forms a silky paste and starts simmering. Add bay leaf. :8 Simmer over medium-low heat, for about a 8-10 minutes until the soup reaches the desired thickness. :9 Return mushrooms  together with it’s juice back to the skillet followed by chicken bouillon and Worcestershire sauce. : 10 Pour in cream. Adjust seasonings with salt and pepper to taste. Lower heat and continue cooking until desired consistency has been reached. :11 Add more cream or chicken broth for desired consistency. Garnish with chopped parsley. Serve hot.", f'{imge_path}/Cream Of Mushroom Soup.jpg', "20mins", "1: 1 tablespoon olive oil or groundnut oil, 2: 1 pound cremini mushrooms , cleaned, roughly chopped, 3: 1 cup diced onion, 4: Salt, 5: 3 tablespoons butter, 6: 2 teaspoon minced garlic, 7: 2 teaspoons fresh minced thyme, 8: 3 tablespoons flour, 9: 1 cup stock (Chicken or Vegetable), 10: 1 canned evaporated milk, 11: 1 bay leaf, 12: 1 teaspoon chicken bouillon, 13: 1/2 tablespoon Worcestershire sauce", "4.1","Soups")

        rec_10 = ("French Onion Soup","1 In a Dutch oven, add olive oil and cook sliced onions on medium heat for around for around 15 to 20 minutes, stirring often to prevent any burns. :2 Add softened butter, salt and pepper into the pot and stir well to melt and coat the onions. :3 Bring the heat to low and let it cook, stirring constantly until onions reach a deep rich brown color or caramelized. :4 Add in the flour and stir. Cook for about 1-2 minutes, enough to remove the flour taste. :5 Then stir in wine while scraping the bottom of the pan to remove browned bits. Now throw in bay leaves, garlic and thyme sprigs. Give it a quick stir. :6 Add beef and chicken stock and bring to a boil. Then simmer for for another 15 – 20 minutes uncovered. Season with salt and pepper. Adjust to taste. :7 While the soup is cooking,  go ahead and prepare fresh bread to top soup. Lightly butter or use olive oil, if desired, to brush both sides of bread slices. :8 You may toast bread in the oven for about 5-7 minutes or toast on a skillet. :9 When soup is ready, add to ramekins or individual serving bowls, if placing in the oven be sure they are oven safe. :10Top it with one or two slices of French toast , then with grated cheese. :11 Place bowls on a baking or cooking sheet and pop it back in the oven for about 2-3 minutes more, or until cheese is melted . :12 Remove, let it cool slightly and serve with more toast if desired.", f'{imge_path}/French Onion Soup.jpg', "50mins", "1: bay leaves, 2: 1 tablespoon olive oil or groundnut oil, 3: 2 tablespoons butter, 4: 3 large white onions (thinly sliced into half moons), 5: 2 tablespoons all-purpose flour, 6: 2 cloves garlic (minced), 7: 1/2 cup white wine, 8: 3 cups beef stock, 9: 2 teaspoons Fresh thyme (plus thyme sprigs for garnish ), 10: 1 cup chicken stock , replace with beef stock, 11: Baguette slices, 12: 1/2- 3/4 cup freshly grated Parmesan or Gruyère, 13: salt and pepper to taste", "4.2", "Soups")

        rec_11 = ("Broccoli Cheese Soup", "1 Melt butter in a pot or Dutch oven over medium heat and saute onions, garlic , Italian  and creole seasoning  for 2-3 minutes or until onions are wilted. :2 Whisk in the flour and cook for a few minutes until it browns or enough to remove the flour taste. :3 Reduce heat to medium-low and slowly pour in evaporated milk and stock while stirring well to dissolve the flour in the liquid. :4 Season with mustard powder and give a quick stir. :5 Allow it to thicken for 5-7 minutes while stirring occasionally.Add in the broccoli florets and let it simmer for 10-15 minutes  or until tender. :6 Then mix in freshly grated cheddar cheese, stir until fully combined. :7 Throw in some grated carrots, if desired, adjust seasoning with salt and pepper and let it cook through for another 2 minutes. :8 Remove from heat and serve in bread bowls or with bread rolls on the side.",f'{imge_path}/Broccoli Cheese Soup.jpg', "25mins", "1: 4 tablespoons butter, 2: 3 Tablespoons flour, 3: 1 medium onion (diced), 4: 1 tablespoon garlic (minced), 5: 1 teaspoon Italian seasoning, 6: 1/2 -1 teaspoon Creole seasoning, 7: 12 ounce can evaporated milk (replace with 1 1/2 cup milk ), 8: 2 cups chicken stock, 9: 1/2 teaspoon mustard powder (optional), 10: 1 large fresh carrot peeled and grated, 11: 1/2- 3/4 pound broccoli florets (cut into small pieces), 12: 1 1/2 – 2 cups sharp cheddar cheese (some reserve for garnish), 13: salt and pepper to taste", "4.2", "Soups" )

        rec_12 = ("Carrot Ginger Soup", "1 Preheat oven to 375 ℉. :2 Line a baking sheet with parchment paper and evenly disperse the carrots, garlic, and sweet potatoes on top. :3 Drizzle with olive oil and place in the oven to roast for one hour, flipping halfway. Set aside. :4 In a medium saucepan, melt butter over medium heat. :5 Add the onion and ginger, sauteing until onions turn translucent, about 2-3 minutes. Season with salt and pepper to taste. :6 When the onions start to brown, take off the heat and transfer to a high powered blender along with the carrots, garlic, sweet potatoes, orange zest, coconut milk, and vegetable broth. :7 Blend on high for 60 seconds or until smooth.Pour into bowls and garnish with pumpkin seeds and serve with bread.",f'{imge_path}/Carrot Ginger Soup.jpg', "1hr 10mins", "1: 2 cups vegetable or chicken broth, 2: 1 tablespoon unsalted butter, 3: 1 large white onion (diced (about 1 cup)), 4: 1 tablespoon fresh ginger (sliced), 5: salt and pepper to taste, 6: 1 pound carrots , peeled and coarsely chopped, 7: 4 whole garlic cloves, 8: 1/2 pound sweet potatoes, 9: 1 tablespoon orange zest, 10: 1 cup coconut milk (can be subbed for almond milk)", "4.2","Soups" )

        rec_13 = ("Groundnut Soup","1 Season chicken with paprika, ½ onions, salt and pepper. Set aside. :2 In a large pot, heat oil over low heat, then add the chicken and sauté stirring, frequently, any browned bits off the bottom of the pot. :3 Blend tomatoes, onions, garlic, parsley and onions. :4 Pour the mixture in the pot of chicken bring to a boil and let it simmer until tender (depending on the chicken). :5 Add the peanut butter and 2 cups of water. Let it simmer for 5 minutes. :6 Adjust the soup thickness with water if necessary .if not, return your soup to the heat and let simmer to desired thickness. :7 Drip a little soup from your stirring spoon. If you are satisfied with the thickness of your soup, serve it.", f'{imge_path}/Groundnut Soup.jpg', "1 hour", "1: 2- 3 pounds chicken, 2: 1 tablespoon paprika, 3: 2-3 Tablespoon oil, 4: 2 tomatoes, 5: 1 medium onion, 6: 4 garlic cloves, 7: 3 tablespoons parsley, 8: 1/2 cup Peanut butter paste, 9: Salt and pepper to taste", "4.1", "Soups")

        rec_14 = ("Cheese Grits","1 Start by adding water, milk, bay leaf and salt to a heavy saucepan. Bring to a boil. :2 Gradually whisk in the grits, until you have added the whole thing in the pot, a little at a time. Keep stirring with a whisk to prevent any lumps. :3 You may have to remove the saucepan from heat while trying to get rid of lumps – if needed. :4 Reduce heat and cook grits at a bare simmer, covered, stirring frequently, until water is fully absorbed and grits thickened. This will take you about 10-15  minutes. :5 Remove grits from heat; add butter and cheese, stirring with a whisk until cheese melts. :6 If cheese is too thick add additional milk. Enjoy piping hot! Topped with more cheese and butter, if desired",  f'{imge_path}/Cheese Grits.jpg', '30mins',"1: 2 cups (473 ml) water, 2: 1 bay leaf ,3: salt and pepper to taste, 4: 3 cups (732 ml) milk (sub with water), 5: 1 cup (159 g) quick grits, 6: 1 cup (113 g) smoked gouda, 7: 1-2 cup (113 – 226 g) sharp cheddar cheese , 8: 3-4 tablespoons (42.53 – 56.70 g) unsalted butter", "4.1", "Cereal" )

        rec_15 = ("Apple Cobbler","1 Pre-heat oven to 350 degrees F (175 degrees C). :2 Spray a  10-inch pie pan or 9 inch  deep pie pan and set aside. You may alternatively use butter to oil the pan. :3 Next Add butter and sugar  in a sauce pan,  let it melt then add apples, lemon juice, cinnamon, nutmeg, vanilla and cornstarch stir until combined . :4 Reduce heat and let it cook for about 7 minutes ,  apples should be firm but tender . Remove from stove and  let it cool. :5 While it cools , mix  the dry ingredients: flour, sugar, salt ,baking powder and soda in a large bowl. :6 Add butter a into flour mixture and mix with hands until the mixture resembles coarse crumbs. :7 Gently stir in buttermilk into dry ingredients until all is moistened. Don’t overwork the dough :8 Pour the apple pie filling into the pan. :9 Then add the dough over the apple pie filling in the pan. Sprinkle with crystalized or brown sugar. :10 Place cobbler  on a baking sheet, just in case you have some drippings from the pie. :11 Bake at 350 degrees for about 40 -45 minutes or until the topping is cooked through and the filling is bubbly. Remove and let it cool down for serving. :12 Serve with vanilla ice cream.",f'{imge_path}/Apple Cobbler.jpg', "50mins", "1: 2 1/2 lbs variety of a good cooking apples such as Granny Smith, Pippin, Fuji, Golden Delicious, Gravenstein, 2: 3 tablespoons unsalted butter, 3: 1/3 cup sugar, 4: 2 tablespoon lemon juice, 5: 1/3 cup brown sugar, 5: 1 1/2 teaspoon cinnamon, 6: 1/4 -1/2 teaspoon ground nutmeg, 7: 1 1/2 tablespoon cornstarch, 7: 1 teaspoon vanilla extract, 8: 2 cups all purpose flour, 9: 2 teaspoon baking powder, 10: 1/4 cup sugar, 11: 1 tablespoon finely chopped crystallized ginger, 12: 1/2 teaspoon baking soda, 13: 1/2 teaspoon salt, 14: 1 cup buttermilk, 15: 1/2 cup (1 stick or 4 ounces) unsalted butter (cut into small cubes)","4.1","Cereal" )

        rec_16 = ("Jamaican Corn Meal Porridge", "1 Add about 2 cups water and 2 cups coconut milk to a heavy large saucepan. Throw in ½ stick cinnamon stick. Bring to a boil. :2 Gradually whisk in the cornmeal, until you have add the whole thing in the pot, a little bit at a time and keep stirring with a wooden spoon to prevent any lumps. :3 Reduce the heat to low and cook until the mixture thickens about 15 minutes. :4 Add flavoring vanilla extract, nutmeg and sweetened condensed milk. :5 Adjust consistency with coconut and/or water if desired. :6 Turn off the heat. Serve piping hot with extra nutmeg, sweeteners an ", f'{imge_path}/Jamaican Corn Meal Porridge.jpg', "25mins", "1: 2 cups water, 2: 1/2 cinnamon stick, 3: 2-3 cups coconut milk drinkable carton variety, 4: 1 cup yellow cornmeal, 5: 1/2 teaspoon salt adjust to taste, 6: 1 teaspoon vanilla extract, 7: Sweeteners (condensed milk; coconut sugar; brown sugar), 8: 1/2 teaspoon nutmeg adjust to taste, 9: 1/2 cup sweetened condensed milk)", "4.2", "Cereal")

        rec_17 = ("Cajun Rice", "1 Rinse rice well and transfer to a heavy-bottomed pot with a lid. :2 Add beef broth and bring to a boil. Reduce heat to medium-low, cover, and let it cook for 18 minutes. Set aside. :3 In a large, heavy sauté pan, sauté chopped bacon until cooked, about 4-5 minutes. Set aside. :4 Then add 2 tablespoons of the oil or more oil to the bacon pan.Throw in the onions, thyme, bay leaf, and garlic, sauté for about 2-3 minutes. :5 Add the chicken liver and ground beef, Creole seasoning, and cook, stirring, for about 5-7 minutes. :6 Add bell peppers, celery, salt, and pepper. Cook, stirring, for 5 minutes. Pour in about 1 1/2 cup stock. :7 Bring to a boil, then lower the heat and simmer for about 5 minutes. :8 Finally, add the rice, mix thoroughly. Cook until the rice is heated through, about 5-7 minutes. If needed, add more stock, to prevent any burns. Do not overcook the rice. Remove from the heat and remove the bay leaf. :9 Stir in the cooked bacon, and green onions. Garnish with parsley, if desired. :10 Serve warm with pepper flakes for heat seekers and/or hot sauce. Enjoy!", f'{imge_path}/Cajun Rice', "50mins", "1: 2 cups (370g) uncooked long-grain rice, 2: 3 1/2 cup (829.5g) water or broth, 3: 2-3 pieces bacon (chopped), 4: 3-4 teaspoons (15g-20g) garlic (minced), 5: 2 teaspoons (2g) fresh thyme, 6: 2 pieces bay leaf, 7: 1/2 pound (226.8g) chicken liver (chopped), 7: 1 pound (453.59) ground beef, 8: 1 green small bell pepper (chopped), 9: 1 stick celery; chopped (about 1/4 cup), 10: 1 1/2 - 2 cups (360ml-480ml) beef stock, 11: 2 teaspoons (8g) Creole seasoning or more to taste, 12: 3-4 pieces green onion scallions (chopped), 13: 1-2 tablespoons (4g) parsley; chopped, 14: 1/2 - 1 cup (125ml-250ml) chicken or beef broth, 15: pepper flakes or hot sauce to taste", "4.1", "Cereal")

        rec_18 = ("Egg Fried Rice", "1 If rice is clumpy, break it up before proceeding. :2 Heat a large wok or skillet on medium-high heat with about 1-2 tablespoons of canola or vegetable oil. Then add rice and soy sauce, quickly stir for about a minute. :3 Add oyster sauce and continue stirring, until fully incorporated. Move the rice to one side of the pan. :4 Then add the eggs and quickly stir to break the eggs apart. Quickly stir the rice and eggs together, for about a minute. :5 Remove eggs and rice mixture and set aside.  :6 Add about a tablespoon of oil or more to the wok or pan. Once hot, add onions, and garlic, stir. Followed with peas and carrots. :7 Finally return the rice. Stir until everything has been fully combined. Add pepper flakes or hot sauce; optional. :8 Adjust seasoning with salt, pepper and soy sauce, if necessary. Garnish with chopped scallion and serve.", f'{imge_path}/Egg Fried Rice.jpg', "15mins", "1: 3-4  tablespoons (42ml-56ml) cooking oil, 2: 4 cups  (1000g) cooked rice, 3: 2 tablespoons (30ml) soy sauce,4: 1 tablespoon  (15ml) oyster sauce, 5: 4 large eggs (lightly beaten), 6: ½ medium onion (sliced) , 7: 2 teaspoons (10g) minced garlic, 8: 1 1/2 cups (200g) frozen mixed vegetables (thawed), 9: 1 green onion (sliced), 10: 1 teaspoon (2g) pepper flakes (optional), 11: salt and pepper to taste", "4.1", "Cereal")

        rec_19 = ("Jollof Rice", "1 Heat oil in a medium saucepan over medium-high heat. :2 Next add onions, thyme, and garlic, cook for about 2 minutes or until onion becomes soft and translucent. :3 Add rice, season with paprika, bouillon, salt, and pepper. :4 Cook stirring often until fragrant, for about 30 seconds. and brown stirring occasionally, for about 2-3 minutes. :5 Pour tomatoes sauce, chicken broth, and hot pepper, if using any into saucepan. :6 Bring to a boil stirring once or twice. Reduce heat to low, cover saucepan and simmer until rice is tender and liquid is absorbed, for 15-18 minutes. :7 Remove pan from heat, let it sit covered for 5 minutes then fluff rice with a fork or serving spoon. Then throw in sauteed veggies and/or beef, chicken and shrimp and mix, if desired :8 Garnish with parsley and serve.", f'{imge_path}/Jollof Rice.jpg', "1hr 10mins", "1: 3-4 tablespoons (42ml-56ml) vegetable oil, 2: 1 medium onion; diced (red or white onions), 3: 2 teaspoons (1.6g) fresh thyme or 1 teaspoon (1g) dried thyme (optional), 4: 1 tablespoon (8g) minced garlic or (9.7g) garlic powder, 5: 3 cups (591g) rice (long-grain; uncooked rice), 6: 1 tablespoon (7g) paprika, 7: 2 teaspoons (4g) chicken bouillon, 8: 1 14-ounce can of tomato sauce or puree, 9: salt and pepper to taste, 10: 4 cups (1000ml) chicken broth or water ( 5 1/4 cups for stove top), 11: 1 scotch bonnet pepper or 3/4 teaspoon hot pepper (omit if cooking for kids), 12: 1 pound (453.59g) vegetables (optional) (can be peas and carrots, green beans or corn), 13: parsley for garnishing", "4.4","Cereal")

        rec_20 = ("Rice Pilaf", "1 Melt butter in a medium sauce pan over medium-high heat. When the butter has melted, add rice and brown stirring occasionally, for about 2-3 minutes.  :2 When rice is brown, add onion, celery, garlic, thyme and cook for a minute until onion become soft and translucent. Season with salt, pepper, Creole seasoning and add bay leaf. :3 Cook stirring often until fragrant, for about 30 seconds. :4 Pour chicken broth into sauce pan and bring to a boil stirring once or twice. :5 Reduce heat to low, cover sauce pan and simmer until rice is tender and liquid is absorbed, for 15-18 minutes. :6 Remove pan from heat, stir in the green onions and zucchini (if using) and let it sit covered for 5 minutes then fluff rice with a fork or serving spoon. :7 Garnish with parsley and serve.", f'{imge_path}/Rice Pilaf.jpg', "55mins","1: 4 tablespoons (56 g) unsalted butter, 2: 1 1/2 cups (277.5 g) uncooked long grain white rice, 3: 1 medium onion (diced), 4: 1 stalk celery (diced), 5: 2 teaspoons (10 g) minced garlic, 6: 1 teaspoon (1 g) minced thyme, 7: 1 teaspoon (5 g)salt, 8: 1/2 teaspoon (1 g) freshly ground black pepper, 9: 1 bay leaf, 10: 1 teaspoon (4 g) Creole seasoning, 11: 3 cups (750 ml)chicken broth, 12: 1-2 green onions (chopped), 13: 2 fresh zucchinis (I used green and yellow ones); diced (optional), 14: 1 tablespoon (3 g) freshly chopped parsley ; for garnish", '4.1', "Cereal")

        rec_21 = ("Mexican Rice", "1 Heat oil in a medium saucepan over medium-high heat, add rice and brown stirring occasionally, for about 2-3 minutes. :2 Next add onions and garlic, cook for about 2 minutes or until onion become soft and translucent. :3 Season with paprika, cumin, bouillon, salt and pepper, add in the jalapenos or chili powder if using. :4 Cook stirring often until fragrant, for about 30 seconds. :5 Pour tomatoes sauce and chicken broth into sauce pan and bring to a boil stirring once or twice. :6 Reduce heat to low, cover sauce pan and simmer until rice is tender and liquid is absorbed, for 15-18 minutes. :7 Remove pan from heat, let it sit covered for 5 minutes then fluff rice with a fork or serving spoon. :8 Garnish with parsley and serve.", f'{imge_path}/Mexican Rice', "1 hour", "1: 3 cups or 600 g rice, 2: 1 medium onion (chopped),, 3: 14 oz can tomatoes sauce, 4: 1/2 cup or 8 fl oz cooking oil, 5: 2 tsp chicken bouillon, 6: 2 tsp or 11.8 g salt, 7: 1 tbsp or 6.90 g paprika, 8: 1 tbsp or 9.84 g garlic powder, 9: 4 cups or 946 ml chicken broth or water, 10: 1 tsp or 2.33 g white or black pepper, 11: 1 1/2 tsp or 3.05 cumin spice, 12: 3/4 tsp or 2.03 chili spice or 1 minced jalapeño pepper (optional; omit if cooking for kids)", "4.1", "Cereal")

        rec_22 = ("Yellow Rice(South African Style)", "1 Heat a saucepan with oil/ butter. Add, ginger, turmeric, curry, and brown sauté for about a minute. :2 Stir in rice to the pan, about 2 minutes. Add 4 cups of stock/water and raisins, bring to a boil. :3 Reduce heat, and simmer. As the rice cooks you may add more stock if needed. :4 Simmer until rice is completely cooked- about 18- 20 minutes depending on how much liquid you added. :5 Fluff and serve", f'{imge_path}/Yellow Rice(South African Style).jpg',"30mins","1: 2-3 tablespoons cooking oil/butter, 2: 1- 2 Tablespoons brown sugar, 3: 2 cups white rice, 4: 1 1/2 teaspoon turmeric powder, 5: 1/2 teaspoon powder ginger, 6: 1/4 teaspoon curry powder (optional), 7: 4 cups chicken stock or water, 8: 1 1/2 teaspoon salt or more adjust to taste, 9: 1/2 cup raisins ", "4.1", "Cereal")

        rec_23= ("Yellow Rice(Indian Style)", "1 Heat a saucepan with oil, then add onions, garlic, ginger , paprika,  curry pepper, cayenne pepper, and white pepper sauté for about a minute. :2 Stir in rice to the pan, about 2 minutes. Add 4 cups of stock/water bring to a boil. :3 Reduce heat, and simmer. Add more stock if needed. Simmer until rice is almost cooked- about 10-12 minutes into cooking. :4 Throw in the peas, cover and continue cooking, for a few more minutes until rice is completely cooked. :5 Fluff and serve.", f'{imge_path}/Yellow Rice(Indian Style).jpg', "30mins", "1: 2-3 tablespoons cooking oil/butter, 2: 1 medium onion chopped, 3: 2 teaspoons minced garlic, 4: 1 teaspoon minced ginger, 5: 1 teaspoon smoked paprika, 6: 1/4 teaspoon curry powder, 7: 1/2 teaspoon white pepper, 8: 2 cups white rice, 9: 1- 1 1/2 teaspoon turmeric powder, 10: 4 cups chicken stock or water, 11: 1 1/2 teaspoon salt or more adjust to taste, 12: 1 cup or more peas defrosted, 13: 1/2 teaspoon cayenne pepper (optional), 14: Black pepper to taste", "4.1", "Cereal")

        rec_24 = ("Coconut Rice", "1 Place rice in a saucepan with water, rinse and sieve out water. :2 Add coconut milk(search for coconut milk in the app to learn to make it), water and salt. :3 Place the saucepan over high heat and, bring to a boil. :4 Stir saucepan then bring to a simmer- heat level should be very low - cover the saucepan tightly with the lid. :5 Continue cooking for about 15-18 minutes. :6 Remove sauce pan from the heat and let it cool, covered. Fluff with fork and serve.", f'{imge_path}/Coconut Rice.jpg', "1 hour 10mins", "1: 2 cups rice, 2: 1- 1 1/2 teaspoon salt, 3: 2 cups water, 4: 2 cups fresh coconut milk; or 1 14 oz can coconut milk", "4.1","Cereal")

        rec_25 = ("Coconut Milk", "1 Hit hard the middle of a coconut with a blunt side of a cleaver or hammer, just enough to crack it. :2 Rotate the coconut, continuing to hit it at the center with the hammer or cleaver. :3 It will split in two eventually at the center or wrap coconut. :4 Place it in the oven for about 10 minutes at 375 degrees F to facilitate removal of the flesh from the shell. :5 Let it cool. Use a spoon to remove the coconut from the shell. :6 Blend coconut in a blender (blendtec or vitamix preferably) on high into a fine consistency. :7 Sieve the coconut mixture using cheesecloth. Squeeze really tight to extract all the milk.", f'{imge_path}/Coconut Milk.jpg', "30mins", "1: 1 mature coconut","4.1","Sauce")

        rec_26 = ("Mushroom Rice", "1 In a large skillet over medium heat, sauté bacon until brown and crisp. This may take about 5-5 minutes. :2 Remove bacon from skillet and transfer to a plate. There will be some bacon drippings left in the pan (about 3 tablespoons). :3 Add about oil / butter to the pan. Throw in mushroom, saute for about 2-3 minutes. :4 Then add onions, garlic, jalapenos, thyme, smoked paprika and creole seasoning. :5 Pour in broth, followed by rice, bacon (I reserved some to top), salt and pepper to taste. :6 Bring to a boil, reduce heat, cover with a lid and simmer until rice is cooked - about 20 minutes or more. Add green onions. :7 Adjust for salt and pepper.", f'{imge_path}/Mushroom Rice.jpg', "40mins", "1: 4-5 thick cut bacon (diced), 2: 1-2 tablespoons butter or oil, 3: 1 medium onion (diced), 4: 3 cups mushroom (about 10 ounce ), 5:2-3 garlic clove (minced), 6: 1/2-1 tablespoon diced jalapenos pepper, 7: 2 teaspoons fresh thyme, 8: 1 tablespoon smoked paprika, 9: 2 teaspoons salt free creole seasoning, 10: 4 cups water or vegetable/ chicken broth, 11: 2 cups washed long grain rice, 12: Salt to taste, 13: 1 -2 green onions", "4.1", "Cereal")

        rec_27 = ("Pineapple Fried Rice", "1 Heat a large wok or skillet on medium high heat with about a tablespoon of canola or vegetable oil. :2 Add shrimp and stir fry for about 3-4 minutes or until slightly pink. Remove shrimp and set aside. :3 Pour in about one tablespoon oil, add pineapple, ginger, onions, green onions, garlic and curry powder. :4 Stir fry for about 3-4 minutes. Push vegetables aside. :5 Add about 1 tablespoons  or more oil, then add eggs mixture, cook without stirring for 5-10 seconds or until the eggs sets on the bottom and is slightly cooked. :6 Add rice and cook for about a minute or 2 quickly, stirring constantly . :7 Return cooked shrimps, peas & carrots, soy sauce and hot sauce. :8 Continue stirring until ingredients have heated through. :9 Adjust seasoning salt, pepper and soy sauce, if necessary. :10 Remove and serve with lime wedges. Garnish with chopped scallion and/or cilantro. Serve warm", f'{imge_path}/Pineapple Fried Rice.jpg',"10mins", "1: 2 tablespoons canola oil, 2: 1/2 pound extra large shrimp (peeled; deveined),3: 1 cup chopped fresh pineapple, 4: 1 teaspoon minced ginger, 5: 1 tablespoon canola oil, 6: 1/2 medium onion (sliced), 7: 2 green onions (chopped), 8: 2 teaspoons minced garlic, 9: 1/4 -1/2 teaspoon curry powder, 10: 3 Large eggs (lightly beaten), 11: 2 cups cooked Long grain rice, 12: 1 cup peas and carrots (Frozen; thawed), 13: 2 tablespoons or more soy sauce (replace with 3 Tablespoon low sodium soy sauce), 14: Hot sauce (Sriracha or your favorite hot sauce) to taste, 15: Salt to taste (optional)", "4.1", "Cereal")

        rec_28 = ("Mexican Cornbread", "1 Preheat the oven to 350 degrees F. Spray a 4×4 baking dish or 10-inch skillet and set aside. :2 In a medium bowl, whisk together the flour, cornmeal, baking powder, sugar, and salt. :3 Whisk in the buttermilk, and the eggs until well combined. :4 Then, add melted butter, jalapeno peppers, green chiles, corn kernels, Monterey Jack, and cheddar cheese. Thoroughly mix to incorporate all ingredients. :5 Scrape down the sides of the bowl. :6 Pour the batter into the prepared baking dish. If desired, sprinkle extra grated cheese and jalapeno peppers. :7 Bake for about 20-22 minutes or until light golden brown and toothpick inserted in the center comes out clean. :8 Let it cool for about 10 minutes. Cut and serve.", f'{imge_path}/Mexican Cornbread.jpg', "50mins", "1: 2 teaspoons (8 g) baking powder, 2: 1 cup (163 g) ground cornmeal, 3: 1 cup (120 g) all-purpose flour, 4: 1/4 cup (49 g) granulated sugar, 5: 1/2 (3 g) teaspoon kosher salt, 6: 1 cup (227 g) buttermilk, 7: 2 eggs, 8: 8 tablespoons (113 g) unsalted butter ( melted), 9: ▢1-2 small chopped fresh jalapeño peppers, 10: 4 oz chopped green chilies; drained (optional), 11: 1 cup (165 g) kernel corn, 12: 1/2 cup (57 g) grated Monterey jack cheese, 13: 1/2 cup (57 g) cheddar cheese", "4.1", "Cereal")

        rec_29 = ("Scalloped Corn", "1 Preheat the oven to 325 degrees F. Spray a 2-quart baking dish with cooking spray. :2 Melt 2 tablespoons butter in a small frypan, then add onion, bell pepper, and Creole seasoning. Sauté for 3-4 minutes. Set aside. :3 In a medium bowl, whisk together the eggs and the half and half. :4 Then add the onion mixture, granulated sugar, salt, drained corn kernels, cheddar cheese, and 1/2 cup of the crushed crackers to a large bowl. Thoroughly mix. :5 Pour over the corn mixture into the prepared casserole dish. :6 Mix remaining crackers and 2 tablespoons melted butter. And spread it over on top of the corn casserole. :7 Add the remaining shredded cheese on top.:8 Bake for about 30 -35 minutes or until edges of the casserole is set and golden brown. Remove from the oven. :9 Top it with parsley.", f'{imge_path}/Scalloped Corn.jpg', "50mins","1: 4 tablespoons melted butter (divided in half), 2: 1 medium onion (diced), 3: 1 bell pepper (diced), 4: 1 teaspoon Creole seasoning, 5: 3 eggs, 6: 1 cup half and half (half cream and half milk), 7: 4 cups corn kernels (fresh or thawed from frozen), 8: 1 tablespoon granulated sugar, 9: 1 teaspoon salt, 10: 1 cup shredded cheddar cheese, 11: 1 1/2 cups buttery crackers such as Ritz (coarsely crushed), 12: 2 tablespoons parsley chopped, 13: cooking spray", "4.1", "Cereal")

        rec_30 = ("Cajun Corn Shrimp Soup", "1 Remove husk from corn and using a sharp knife, cut the kernels from the cob from top to bottom and gather the kernels with their juices in a large bowl. :2 Use the back of a knife to scrape the residual corn from the cobs. :3 Repeat with the remaining corn. Set aside. You may also use frozen corn. :4 Next, generously season the shrimp with creole seasoning(search for recipe). Heat oil/butter over medium heat in a heavy-bottomed Dutch. :5 Sauté the shrimp for about 3 -5 minutes and set aside. :6 In the same pan, add onions, garlic, bay leaf, and thyme sauté for about a minute. :7 The add celery sticks, red bell pepper, smoked paprika, and Creole Cajun seasoning. Continue cooking for about 5-7 minutes until onions are soft. :8 Add the tomato paste and cook for further minute or two before pouring in the chicken stock, corn, white pepper and potatoes. :9 Bring to a boil and let it simmer for about 20 -30 minutes or until the potatoes are fully cooked and tender - enough to thicken the soup. :10 Top with sautéed shrimp (you may also add shrimp, if desired, at the last  3-5 minutes before turning off the stove ).  :11 You do not want to overcook the shrimp. Garnished with chopped flat-leaf parsley.", f'{imge_path}/Cajun Corn Shrimp Soup.jpg', "55mins", "1: 2 tablespoons canola oil, 2: Creole cajun seasoning(search app, for this recipe), 3: 1 large onion (diced), 4: 1 tablespoon minced garlic, 5: 1 large bay leaf, 6: 2 teaspoons fresh thyme, 7: 1/2 cup chopped celery sticks, 8: 1 red bell pepper (diced), 9: 1 teaspoon smoked paprika, 10: 1-2 teaspoon Creole Seasoning, 11: 1-2 tablespoons tomato paste, 12: 4-5 cups warm chicken stock (adjust thickness with more or less), 13: 5 ears of corn (about 3 cups), 14: 1 teaspoon white pepper, 15: 1 tablespoon chopped flat-leaf parsley, 16: 1 potato (about half pound), 17: 1 pound large shrimp (peeled and deveined shrimp)","4.1","Soups")

        rec_31 = ("Creole Cajun Seasoning","1 Combine all the ingredients in a bowl, or Jar and stir so that all the ingredients have been fully combined. :2 Store in any airtight container (or zip lock bag) and start adding to your proteins and", f'{imge_path}/Creole Cajun Seasoning.jpg',"10mins", "1: 3 Tablespoons onion powder, 2: 3 Tablespoons garlic powder, 3: 1 1/2 Tablespoons black pepper, 4: 1 1/2 Tablespoons white pepper, 5: 6 Tablespoons paprika, 6: 1/2 - 1 Tablespoons cayenne pepper (adjust to suit taste buds), 7: 1 1/2 Tablespoons oregano, 8: 1 Tablespoon dried parsley, 9: 1 1/2 Tablespoons dried thyme, 10: 1 1/2 Tablespoons dried basil", "4.1", "Sauce")

        rec_32 = ("Cornchaff","1 Rinse dry red beans and pick through and discard any foreign object.( You don't have to do this if you are using the package beans). :2 Add th3 beans to a large pot covering with 3-4 inches of cold water.Cover and let sit overnight or 6 to 8 hours. :3 Drain the soaked beans, rinse, and place the beans in a Dutch oven or pressure cooker. :4 Follow instructions for cooking beans in your pressure cooker. :5 It takes roughly between 8 to 12 minutes to cook. If not using a pressure cook, cook the beans for about 1 to 1 1/2 hours until tender. :6 Drain the cooked beans and add corn to the pot and stir. :7 Add palm oil, onions, tomatoes, crayfish, smoked fish, garlic, ginger, smoked paprika , chicken bouillon and salt. :8 Then pour about 2 – 3 cups or more of water or chicken stock bring to a boil and let it simmer for all the flavors to come together about 20 -25 minutes, stirring occasionally. :9 You can smash the cornchaff here for a the perfect adalu , if you like it smash. :10 Adjust for seasonings and serve.", f'{imge_path}/Cornchaff.jpg', "3 hours", "1: 1-2 cups smoked turkey; fish; chicken, 2: One pound dried beans any variety (sub 3 16 ounce canned beans), 3: One pound corn sweet boiled corn or any kind, 4: 2 medium tomatoes diced, 5: 1 1/2 teaspoons minced garlic, 6: 1 teaspoons grated ginger, 6: 1/2 medium onion diced, 7: 1/2 cup crayfish smoked/dried shrimp optional, 8: 1/2 - 3/4 cup palm oil, 9: 1 tablespoon smoked paprika, 10: Salt and pepper to season, 11: 1-2 Tablespoons Chicken bouillon optional", "4.1","Cereal")

        rec_33 = ("Koki Corn", "1 Remove husk from corn and using a sharp knife, cut the kernels from the cob from top to bottom and gather the kernels with their juices in a large bowl. :2 Use the back of a knife to scrape the residual corn from the cobs. Repeat with the remaining corn. Reserve the corn for later use. :3 Using a food processor or blender, pulse the corn with 1 cup of water until it is coarsely ground. You do not want to puree the corn. :4 In a bowl combine the mixture with cornmeal, salt and palm oil mixture. Finally add the chopped spinach and set aside. :5 Cut the banana leaves into rectangles, remove any ugly edges, submerge them in water to clean and drain pat- dry. Use saran wrap if banana leaves are not available. :6 The leaves must be heated and wilted over an open high flame to make them flexible. :7 Then, cut the aluminum into large squares/ rectangles and place a piece of the leaf / saran wrap on it. Repeat the process and set them aside. :8 Place the mixture of Koki-corn on the leaf about 1 cup. :9 Then quickly fold aluminum over it, and press sides into a rectangle shape making sure to press inwards so none of the Koki runs out. :10 Then fold the sides in to seal twice. Repeat the process and set them Place the Koki corn in the pot with reserved cobs. :11 Line the bottom of a large stock pot with reserved cobs. :12 Add enough water to almost but not quite submerge the cobs. Cover the cobs with a layer aluminium foil . :13 The Koki corn should not come in contact with the water so they don’t get soggy.", f'{imge_path}/Koki Corn.jpg', "1hr 35mins", "1: 5 ears fresh corn, 2: 1 cup water, 3: 1 cup corn meal, 4: 3 cups spinach, 5: 1 teaspoon salt, 6: 2-3 tablespoon palm oil, 7: Foil paper/ Banana/Plantain Leaves/ Saran Wrap", "4.3","Cereal")

        rec_34 = ("Koki Bean", "1 Soak peeled beans in water for about an hour to overnight to tenderize the beans to facilitate blending. Cut Aluminum foil paper about 6 and set aside. :2 Cut the banana leaves into rectangles, remove any ugly edges, submerge them in water to clean and drain pat dry. :3 Use saran wrap, if banana leaves are not available. :4 The leaves must be heated and wilted over an open high flame to make them flexible. Chop onions, habanero and set aside. :5 Lightly warm palm oil in a small skillet or saucepan for about a minute or two until completely melted. :6 In a food processor or blender puree beans, onions and  pepper with a cup or more of water or until it has reached desired consistency. :7 Pour the mixture into a large bowl; add palm oil, spinach. Mix everything together, then, season to taste with Maggie and salt. :8 Make sure you have used up all the water. :9 Place the mixture of Koki-beans on the leaf about 2 cups. :10 Then quickly fold the Koki together to form a little purse. Repeat the process and set them. :11 Line the bottom of a large stockpot with aluminum foil or remaining leaves or stalk on hand to create a steamer. Add enough water. :12 Steam cook koki for about an hour and 30 minutes, add water as necessary to prevent any burns. :13 Remove and let it cool for about 10 minutes, then serve.", f'{imge_path}/Koki Bean.jpg',"3hr 30mins", "1: 2 cups skinless black-eyed- peas(beans), 2: 1/2 medium onion, 3: 1/2 Scotch bonnet or habanero pepper (optional), 4: 1 cup palm oil, 5: 3 cups chopped fresh spinach(or coco leaves), 6: 3 1/2 cups water, 7: 2 Maggie cubes or 2 teaspoon bouillon, 8: 3 teaspoon salt or more", "4.3", "Cereal")

        rec_35 = ("Beans", "1 Rinse dry beans and pick through and discard any foreign object. (I did not have to do this because I used the package beans,). :2 Add beans to a large pot covering with 3-4 inches of cold water. Let it sit overnight. :3 Drain the soaked beans, rinse, set aside. :4 Heat oil in a Dutch oven or large pot. :5 Cut sausage and turkey into 1inch chunks and add to oil. :6 Saute for about 3- 5 minutes, stirring frequently any browned bits off the bottom of the pot, until brown. :7 Then add onions, garlic, celery, bell peppers, bay leaves, thyme, and sprig fresh thyme to the pot. :8 Season vegetables with Creole seasoning, paprika, and cayenne, if using. :9 Saute for about 5 minutes, or until vegetables start to wilt. :10 Place the rinsed beans in the pot, stir, then pour in broth or water. :11 Bring to a boil. Reduce heat to a simmer and cook, uncovered, for about 1 1/2 -2 hours, stirring occasionally, or until beans are tender and slightly thickened. :12 Note: Add more stock or water if the mixture becomes dry and thick. :13 The texture of the beans should be thick – somewhat creamy but not watery. :14 Remove the bay leaves and thyme sprig. :15 Taste and adjust for seasonings with pepper and salt if needed. Serve over cooked rice and garnish with green onions.", f'{imge_path}/Beans', "2hr 30mins", "1: 2 teaspoons paprika, 2: 1 pound (450g) red kidney beans, 3: 1/4- 1/3 cup vegetable oil (or canola), 4: 1 pound (450 grams) andouille sausage sliced, 5: 1/2 pound (225 grams) hamhock or smoked turkey chopped, 6: 1 large onion diced, 7: 2 tablespoons minced garlic (about 6 medium size garlic), 8: 1/2- 3/4 cup celery diced (about 1 medium rib celery), 9: 1 large bell pepper diced, 10: 2 -3 bay leaves, 11: 1 teaspoon thyme, 12: 1 sprig fresh thyme, 13: 2 teaspoons Creole spice(search app, for this recipe), 14: 1 teaspoon cayenne pepper (optional)", "4.3","Cereal")

        rec_36 = ("Tossed Salad", "1 In a large salad bowl, layer romaine lettuce, followed by tomatoes, cucumber, onion, carrots, radish, and optional ingredients. :2 Drizzle desired dressing on the salad, toss to combine. Serve immediately.", f'{imge_path}/Tossed Salad.jpg', "15mins", "1: 2 heart romaine lettuce; wash dried and chopped , 2: 1 cup or more grape tomatoes; sliced , 3: 2 cups diced cucumber; seeded and sliced, 4: 1 carrot; peeled and shredded, 5: 1/2 red onion sliced , 6: 1/2 cup sliced radish (optional), 7: 1/4 cup chopped bacon (optional), 8: 1 avocado pitted and sliced or diced  (optional) ", "4.1","Salads")

        rec_37 = ("Chef Salad","1 In a large mixing bowl, whisk together yogurt, olive oil, mustard, honey, vinegar, lemon juice, orange juice, garlic, shallots, salt, and pepper. :2 Assemble salads in individual bowls or in a large serving bowl, top with dressing and enjoy!", f'{imge_path}/Chef Salad.jpg', "25mins","1: 5 large eggs; hard-boiled, 2: 1 large head romaine lettuce; washed; dried and chopped, 3: 1 cup cherry tomatoes; halved, 4: 1 large cucumber; chopped about 1 cup, 5: 1 large carrot; shredded about 3/4 cup, 6: 1 block mild cheddar cheese; cubed abut 2 cups, 7: 2 cups ham; cubed, Salad Dressing, 1: 1/2 cup plain Greek yogurt, 2: 1/4 cup extra virgin olive oil, 3: 1/4 cup Dijon mustard, 4: 4 tablespoons honey , 5: 2 tablespoons apple cider vinegar, 6: 2 tablespoons lemon juice, 7: 1 tablespoon fresh squeezed orange juice , 8: 2 cloves garlic; minced, 9: 2 tablespoons shallots; minced, 10: salt and pepper to taste", "4.1","Salads")

        rec_38 = ("Shaved Brussel Sprouts Salad","1 In a medium mixing bowl, mix together yogurt, olive oil, mustard, honey, vinegar, lemon and orange juice, garlic, shallots, salt and pepper. :2 Refrigerate until ready to use. :3 In a large mixing bowl, toss shaved brussels sprouts with salad dressing to taste. :4 Top with cheese, dates and apple slices. Drizzle with more dressing, toss and serve.",f'{imge_path}/Shaved Brussel Sprouts Salad.jpg',"20mins", "1: 1/2 cup smoked gouda; sliced, 2: 1 lb brussels sprouts; thinly sliced, 3: 1 red apple; thin sliced, Dressing, 1: 1/2 cup plain Greek yogurt, 2: 1/4 cup extra virgin olive oil, 3: 1.4 cup Dijon mustard, 4: 2 tablespoons apple cider vinegar, 5: 4 tablespoons honey , 6: 2 tablespoons lemon juice, 7: 1 tablespoon fresh squeezed orange juice, 8: 2 cloves garlic; minced, 9: 2 tablespoons shallots; minced, 10: salt and pepper to taste", "4.1","Salads" )

        rec_39 = ("Tropical Fruit Salad Recipe","1 Combine all fruits in a large bowl. When ready to serve, mix the fruit pulps and lime and lemon juice. :2 Add simple syrup as needed. Pour over the fruit salad. :3 Adjust with more water and/or  simple syrup(search the app to learn the simple syrup). Refrigerate until ready to use. :4 Serve cold.", f'{imge_path}/Tropical Fruit Salad Recipe.jpg', "1hr 30mins", "1: 1/2 lime Juice, 2: 1/2 lemon juice, 3: 1-2 cups passion fruit pulp, 4: 1-2 guava or pineapple juice or pulp, 5: ½ large Pineapple (peel and cut into small dice), 6: 2 ripe mangoes (peeled and cut into small dice ), 7: 1/2 large or 1 small papaya (peeled and cut into small dice), 8: 4-6 kiwi fruits (peeled and cut into small dice), 9: Cold water (adjust to taste )", "4.1","Salads")

        rec_40 = ("Simple Syrup(Tropical Fruit Salad)", "1 In a medium saucepan combine sugar and water. Bring to a boil, keep stirring until sugar has dissolved- about 5-7 minutes. Let it cool.", f'{imge_path}/Simple Syrup(Tropical Fruit Salad).jpg', "15mins", "1: 2 cups water, 2: 3/4 cup sugar replace with honey, or any sweetener", "4.1", "Sauce")

        rec_41 = ("Watermelon Salad","1 Start by cutting off both ends of the watermelon. Then slice watermelon into half and cut in slices. :2 Place each slice on the cutting board. Then cut out the skin of the watermelon slices, as you cut it out rotate the slice.  :3 Be sure to cut out all the white part. Cut it into cubes and place in a large bowl. :4 In a small mixing bowl, whisk together olive oil, lemon juice, red vinegar, lime juice, cayenne, honey, hot sauce, salt, and pepper. :5 In a large bowl, combine watermelon, cucumber, feta, onion, and chopped mint. Toss with dressing. :6 Garnish with mint. Refrigerate until ready to serve.", f'{imge_path}/Watermelon Salad.jpg', "20mins", "1: 6  cups (or 4 pound) seedless watermelon , 2: 1 cucumber; seeded and small diced, 3: 1/2 cup (66g) feta cheese or sub with queso Blanco, 3: 1/2 cup (57.5g) red onion; thin sliced, 4: 1 cup (25g) coarsely chopped mint leaves; some whole for garnish, Watermelon Salad Dressing, 1: 3 tablespoon s (42ml) extra-virgin olive oil, 2: 3 tablespoons (45ml) fresh lemon juice, 3: 2 tablespoon s (30ml) red vinegar, 4: 1 tablespoon (15ml) lime juice, 5: 1 tablespoon (18g) honey, 6: 1/4 -1/2 teaspoon (0.5g-1g) cayenne pepper, 7: 1/2 teaspoon (2.5g) hot sauce, 8: salt to taste, 9: 1/2 teaspoon (1g) freshly ground pepper", "4.1", "Salads")

        rec_42 = ("Panzanella Salad","1 Heat the oil in a skillet or cast iron over medium heat.  You may add more oil as you cook. :2 Add bread cubes, let it sit for a minute, then toss frequently. :3 If bread is browning too fast, adjust heat Continue browning for about 8-10 minutes, or until nicely browned. Or preheat oven to 425 degrees F. :4 Spread out bread cubes on a parchment-lined baking sheet. :5 Drizzle about 1-2 tablespoons oil and a pinch of salt over the bread cubes. :6 Then bake in a preheated oven for about 7-10 minutes until dried out and pale golden brown at the edges. :7 Remove from the oven and let it cool on a wire rack. In a small mixing bowl, combine tomatoes, onions, bread cubes, cucumber, mozzarella, and olives. :8 In a medium bowl, combine remaining, garlic, vinegar, Dijon mustard salt, and black pepper to taste. :9 Add olive oil until the mixture is thickened. Stir in thyme and oregano. :10 Pour dressing over the bowl of tomatoes. :11 Toss to fully combine, adjust seasoning to taste. Top with capers and basil before serving, if desired.", f'{imge_path}/Panzanella Salad.jpg',"20mins","Panzanella Bread, 1: 1/2 baguette; stale cut into 1-inch cubes (about 3 cups), 2: 1-2 tablespoons (14ml-28ml) olive oil, 3: 1 teaspoon (5g) sea salt, 4: 2 cups (298g) mixed cherry tomatoes; halved, 5: 1/4 cup (28.75g) red onion; thinly sliced, 6: 1/2 cup (66g) fresh mozzarella; chopped or torn into pieces, 7: 1 cucumber , sliced half-moon (about 2 cups), 8: 1/2 cup (65g) kalamata olives, 9: 1/4 cup (6g) fresh basil; torn in pieces, 10: 1-2 tablespoon s (8.6g-17.2g) capers; optional, Dressing, 1: 2-3 garlic cloves , grated into a paste , 2: 2-3 tablespoons (30ml-45ml) red wine vinegar, 3: salt and black pepper to taste, 4: 1/2 teaspoon (2.5g) Dijon mustard, 5: 3 tablespoons  (42ml) olive oil, 6: ½ teaspoon  (0.5g) thyme; minced, 7: 1 tablespoon (3g) oregano; chopped ","4.1","Salads")

        rec_43 = ("African Beef Stew","1 Boil beef with salt, pepper and some chopped onions in a medium pot until tender. :2 It will take approximately 30 minutes or more, depending the cut of beef and how you like your beef cooked. :3 I sometimes use the pressure cooker to shorten the process. Reserve the stock for later use. :4 Add 1 cup oil to the pot/pan and brown the beef for about 5-10 minutes. Remove and set aside. :5 In a blender, blend the onions, tomatoes, garlic, parsley, celery, thyme, basil  and scotch bonnet pepper. :6 Gently pour the blend of puree ingredients, and tomatoes puree  in the saucepan. l7 Add curry powder, white pepper , smoked paprika and bouillon powder bring to a boil, reduce heat and simmer for about 30 minutes. :8 Then return browned  beef and simmer for another 10 to 15 minutes. :9 Stir the pot frequently to prevent the sauce from sticking to the pot. -Occasionally adding beef stock or water as needed to prevent burns :10 Finally add green onions. Adjust seasonings, sauce consistency with water/stock and salt. Serve warm with desired side dish.", f'{imge_path}/African Beef Stew.jpg',"1hr 30mins"," 1: 1-2 pound stew beef;  cut in small pieces, 2: 1 medium yellow onion, 3: 1/2 -1 cup oil (Canola, Vegetable or Corn); adjust as needed, 4: 1/4 cup chopped parsley, 5: 4 peeled garlic cloves, 6: 4 roma tomatoes; they are less acidic, 7: 3-4 tablespoon celery leaves, 8: 1/2 -1 scotch bonnet pepper; optional, 9: 1-2 basil leaves, 10: 1 teaspoon fresh thyme, 11: 1 canned tomatoes sauce; 14 ounce, 12: 1 teaspoon white pepper, 13: 1/2 teaspoon curry powder, 14: 1-2 teaspoons smoked paprika, 15: 1 tablespoon Maggie powder or beef bouillon powder, 16: 1-2 green onion; sliced, 17: Salt to taste","4.1","Stews")

        rec_44 = ("Beef Bourguignon", "1 Preheat oven to 350°F (175°C). :2 Pat dry the beef with a paper towel, lightly season with salt and pepper. Sprinkle flour on the beef and mix. Set aside.  :3 Add the chopped bacon to a large Dutch oven or pot. Sauté the bacon over medium heat for about 6-7 minutes until crisp and browned. :4 Remove bacon with a slotted spoon and place bacon on a plate for later use. Drain excess bacon fat from the pan and leave about1-2 tablespoons in the pan. :5 Add more oil if you do not have enough bacon fat left. :6 Place the beef, in batches, in the same pot as the bacon fat and sauté until browned on both sides- 2-3 minutes.  :7 Remove beef from the pan and place it with the bacon. :8 Add more oil or bacon fat in the pot, as needed (1-2 Tablespoons more).  :9 Then add onions, thyme, garlic, and bay leaves. Sauté for 3-4 minutes or until onions are slightly translucent. :10 Throw in the mushrooms and continue cooking for about 5 more minutes. Remove and set aside. :11 Throw in celery and carrots and saute for about 1-2 minutes.:12 Deglaze the pan by pouring in the red wine, beef stock, and water in the pan. Scrape the sides of the pan, using a wooden spoon. :13 Add the tomato paste and stir until fully incorporated. :14 Return the beef and mushroom mixture back to the pot. Bring to boil, add beef bouillon or cubes (if desired), and lightly season with salt and pepper. :15 Cover the pot and transfer to the lower part of the oven and simmer for 1 1/2 -2 hours or until the meat is tender. Adjust cooking times to desired preference beef tenderness. :16 While you cook, be sure to check on the pot if it has enough liquid. Add more water as needed. :17 Once the beef is ready, taste and adjust seasonings accordingly with more salt and or pepper. :18 If using pearl onions, sauté for about 3-5 minutes and place on top of the bourguignon together with reserved bacon. :19 Garnish with parsley and served with mashed potatoes or noodles. Enjoy!", f'{imge_path}/Beef Bourguignon.jpg',"2hr 5mins","1: 2 1/2 - 3 pounds (1133.98g-1360.77g) boneless beef chuck; trimmed and cut into chunks, 2: Salt and pepper to taste, 3: 1/4 cup (31.25g) all-purpose flour, 4: 8 ounces (226.8g) bacon; diced, 5: 1 pound (453.59g) cremini mushrooms; sliced, 6: 1/2 cup (57.5g) chopped onions, 7: 1 tablespoon (8g) minced garlic, 8: 2 small bay leaves, 9: 1/4 teaspoon (1g) thyme, 10: 4 celery stalks; diced, 11: 3-4 carrots; sliced or cut in chunks, 12: 1 cup (235ml) dry red wine (preferably Pinot Noir), 13: 3 cups (720ml) beef stock, 14: 1 cup (237ml) or more water, 15: 1 tablespoon (16g) tomato paste, 16: 1 - 2 teaspoons (2g-4g) beef bouillon; cubes or powder, 17: 15 - 20 small pearl onions; optional", "4.1", "Stews")

        rec_45 = ("Brown Stew Chicken", "1 Pat dry the chicken with paper towels. Then place chicken in a bowl and season with salt and pepper according to preference. :2 Followed by the chicken bouillon powder, ginger, garlic, white pepper, thyme, paprika, and green onions. :3 Thoroughly mix chicken with a spoon or with hands until they are well coated, cover tightly and set aside in the fridge.  :4 Marinate for about at least an hour or preferably overnight. :5 When ready to cook, discard any excess particles from the chicken and reserve for later use. Heat up a large pan (I used a 12 inch cast iron ) with about 2 tablespoons oil. :6 Brown the chicken about 3-4 minutes until chicken is a golden brown; remove and place on a plate. :7 Drain any excess oil from the skillet and leave about 2-3 tablespoons of oil. :8 In the same pan, add onions, garlic, thyme, hot sauce, paprika, sugar, browning sauce, ketchup, bell peppers (if desired add some or all of the bell peppers towards the last 10 minutes of cooking), and salt to taste. :9 Stir for about 2-3 minutes until onions is translucent. Add the remaining marinade from the chicken . : 10 Deglaze pan with water. Bring to a boil and return the brown chicken back to the pan. :11 Cover and cook for about 25 minutes, more or less or until chicken has been cooked through and no longer pink and sauce thickens, slightly. :12 Adjust for salt, pepper and soup consistency with more water as you cook. :13 Turn off the stove, remove and serve with Caribbean Rice and Beans.", f'{imge_path}/Brown Stew Chicken.jpg', '1hr 50mins', "Chicken Marinade, 1: 1 3 1/2 - 5 pound chicken; cut in 10 pieces, 2: salt and pepper to taste , 3: 1 teaspoon  (2g) bouillon chicken powder, 4: 1/2 teaspoon (1g) minced ginger, 5: 1 teaspoon (5g) minced garlic, 6: 1/2 teaspoon (1g) white pepper, 7: 1 teaspoon (0.80g) fresh thyme, 8: 1/2 teaspoon (1g) paprika, 9: 2 green onions; diced, Brown Chicken Stew, 1: 2 tablespoons (28ml) or more canola oil, 2: 1 medium onion; diced (about 1 1/2 cups), 3: 2 teaspoons (10g) minced; garlic, 4: 1 teaspoon fresh thyme, 5: 1 teaspoon (4.7g) hot sauce sub chili sauce, 6: 1 1/2 teaspoon (3g) paprika, 7: 1 tablespoon (12.5g) brown sugar, 8: 1-2 teaspoons (5-10ml) browning sauce, 9: 2-3 tablespoons (32-48g) ketchup, 10: salt and to taste, 11: 1-2 cups (237-474g) chicken broth/water, 12: 2 small bell pepper; red or green; sliced ", "4.1","Stews")

        rec_46 = ("Chicken Stew (African Style)", "1 Season chicken with, salt, pepper, and Creole seasoning. Set aside. :2 In a large pot, heat oil over medium heat, until hot, and then add the chicken and sauté stirring, frequently, any browned bits off the bottom of the pot, until chicken is brown. :3 If using fresh tomatoes, blend tomatoes, onions, garlic, and onions. Pour the tomatoes blend in the pot of chicken. :4 Bring to a boil and let it simmer until tender (depending on the chicken) about 20- 30 minutes, frequently stirring the saucepan to prevent burns. :5 If using tomato sauce; add the onion, sauté until tender, about 4-5- minutes. :6 Pour tomato sauce, curry powder, smoked paprika, thyme, bay leaf, garlic, and bouillon powder. :7 Bring to a boil and let it simmer for about 20-30 minutes. Add about 2 cups of water to the pan. :8 Add carrots, green onions, parsley. Cook for another 5 minutes. Adjust the thickness of soup with water or stock. :9 Season with salt according to preference. Remove bay leaf. Serve over warm rice.", f'{imge_path}/Chicken Stew (African Style).jpg',"1 hour", "1: 3-3 1/2 pound (1362g-1589g) chicken cut in pieces, 2: 1-2 teaspoons (4g-8g) Creole Seasoning, 3: salt and pepper to taste, 4: 1/4-1/2 cup (62.5g-125g) oil (canola; olive or vegetable oil), 5: 5-6 Roma tomatoes or 2 cups tomato puree, 6: 1 medium onion; sliced, 7: 1 tablespoon (8g) minced garlic (about 3-4 cloves), 8: 1 tablespoon (7g) paprika, 9: 1 1/2 teaspoon (1.5g) dried thyme, 10: 1 bay leaf, 11: 1/4 teaspoon (0.5g) curry powder, 12: 1 tablespoon maggi or bouillon granules, 13: 2 cups (474ml) water, 14: 2 green onion chopped whites and green parts, 15: 3 tablespoon (12g) parsley, 16: 1-2 cups (128g-256g) sliced carrots", "4.1","Stews")

        rec_47 = ("Jamaican Oxtail Stew", "1 Season oxtail with, salt and pepper. Set aside. :2 In a large pot, heat oil over medium heat, until hot, and then add the oxtail sauté stirring, frequently, any browned bits off the bottom of the pot, until oxtail is brown. :3 If desire drain oil and leave about 2-3 tablespoons. :4 Add onions, green onions, garlic, thyme, all spice, worcestershire,smoked paprika, stir for about a minute. :5 Throw in scotch bonnet pepper, tomato paste, bouillon and curry powder, stir for another minute. :6 Then add about  4-6 cups of water , it's best to start with 4 cups , then add as needed . :7 Bring to a boil and let it simmer until tender (depending on the oxtail size and preference) about 2- 3 hours, occasionally stirring the saucepan. :8 About 20-30 minutes before you remove from the stove add broad beans. Adjust thickness of soup with water or stock. :9 Season with salt according to preference.", f'{imge_path}/Jamaican Oxtail Stew.jpg',"2hr 15mins", "1: 2 -3 tablespoon cooking oil, 2: 1- 2 pounds oxtail cut up medium pieces, 3: 1 onion chopped, 4: 2 teaspoon minced garlic, 5: ▢1- teaspoon fresh chopped thyme, 6: 1/2 teaspoon smoked paprika, 7: 1 tablespoon ketchup /tomato paste, 8: 1 Whole Scotch bonnet pepper, 9: 2 green onions chopped, 10: 5-6 Whole pimento seeds (allspice), 11: 1  Tablespoon Worcestershire sauce, 12: 1- teaspoon curry or more adjust to preference, 13: 15 ounce can butter beans; rinsed and drained, 14: 1 teaspoon browning (optional), 15: 1 Tablespoon bouillon powder or cube (optional), 16: Salt to taste","4.1", "Stews")

        #Now add the recipes
        # def create_recipe(a):
        #     for a in range(1,48):
        #         create_Recipes(conn, f'rec_{a}')
        
        add_recipe()
            




#Call the main() funct
if __name__ == '__main__':
    main()